---
- name: Configure AWS CLI
  blockinfile:
    path: "{{ jenkins_home }}/.aws/config" 
    state: present
    user: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    block: |
      [default]
      region = {{ aws_region }}
      output = json


- name: Configure Git
  blockinfile:  
    path: "{{ jenkins_home }}/.gitconfig"
    state: present
    user: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0644
    block: | 
      [credential]
        helper = !aws --profile CodeCommitProfile codecommit credential-helper $@
        UseHttpPath = true
