- name: Copy Jenkins-Backup Job
  copy:
    src: jobs/
    dest: "{{ jenkins_home }}/jobs"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  notify: restart jenkins

- name: Copy Job Configurations
  copy:
    src: "{{ jenkins_job_configs }}"
    dest: "{{ jenkins_home }}/jobs"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  when: jenkins_job_configs is defined
  notify: restart jenkins
